services:
  - type: web
    name: pdf_summari
    env: python
    plan: free
    healthCheckPath: /
    buildCommand: pip install -r requirements.txt
    startCommand: python manage.py migrate --noinput && python manage.py collectstatic --noinput && gunicorn pdf_summari.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: SECRET_KEY
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "yourdomain.com"
